#ifndef BASICMEDIAPLAYER_GLOBAL_H
#define BASICMEDIAPLAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASICMEDIAPLAYER_LIBRARY)
#  define BASICMEDIAPLAYERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASICMEDIAPLAYERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASICMEDIAPLAYER_GLOBAL_H
