#ifndef AUDIODEVICES_GLOBAL_H
#define AUDIODEVICES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUDIODEVICES_LIBRARY)
#  define AUDIODEVICESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AUDIODEVICESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AUDIODEVICES_GLOBAL_H
