#ifndef PLAYLISTMANAGER_GLOBAL_H
#define PLAYLISTMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLAYLISTMANAGER_LIBRARY)
#  define PLAYLISTMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLAYLISTMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLAYLISTMANAGER_GLOBAL_H
